# Generated by Django 5.0.2 on 2024-02-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0004_artwork_name'),
        ('art_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='art_api.artwork'),
            preserve_default=False,
        ),
    ]
