# Generated by Django 5.0.2 on 2024-02-25 20:32

import art_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0002_artwork_uploade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.JSONField(blank=True, null=True, validators=[art_api.models.validate_size]),
        ),
    ]
