# Generated by Django 5.0.2 on 2024-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0003_artwork_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
