# Generated by Django 5.0.2 on 2024-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0004_alter_artwork_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
