# Generated by Django 5.0.2 on 2024-02-21 13:04

import art_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=art_api.models.user_directory_path)),
                ('price', models.PositiveIntegerField()),
                ('size', models.JSONField(blank=True, null=True, validators=[art_api.models.validate_size])),
                ('uploade_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(related_name='voted_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
