# Generated by Django 5.0.2 on 2024-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0003_alter_artwork_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
