# Generated by Django 5.0.2 on 2024-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selledartwork',
            name='price',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
